import { RoomType, Task } from './types';

const raw: Record<RoomType, string[]> = {
  kitchen: [
    'Wipe down the counter',
    'Fill a glass with water and drink it',
    'Put 3 dishes in the sink or dishwasher',
    'Open the fridge and name 3 items inside',
    'Throw away one piece of trash',
    'Organize the utensil drawer',
    'Wipe down the stovetop',
    'Take out the recycling',
    'Refill the napkin holder',
    'Check the pantry for expired food',
    'Make a piece of toast',
    'Wipe the microwave door',
    'Straighten the chairs at the table',
    'Check if the trash needs to be taken out',
    'Pour yourself a snack in a bowl',
  ],
  bathroom: [
    'Fold the hand towel neatly',
    'Check the toilet paper roll and refill if needed',
    'Wipe down the sink',
    'Straighten the items on the counter',
    'Check under the sink for supplies',
    'Close the shower curtain',
    'Wipe the mirror if it is smudged',
    'Empty the small trash can',
    'Check the soap dispenser level',
    'Line up the toiletries neatly',
    'Wash your hands with soap',
    'Fluff the bathmat',
    'Check that the light works',
    'Straighten the towels on the rack',
    'Close the toilet lid',
  ],
  'living-room': [
    'Fluff two couch pillows',
    'Fold a blanket',
    'Straighten the remotes on the table',
    'Pick up 3 stray items off the floor',
    'Dust a visible shelf',
    'Turn a lamp on and back off',
    'Straighten the books on a shelf',
    'Check under the couch cushions for lost items',
    'Wipe down the coffee table',
    'Close the curtains or blinds',
    'Turn the TV on and back off',
    'Line up the shoes by the door',
    'Water a houseplant if there is one',
    'Adjust a crooked picture frame',
    'Sweep a corner of the room',
  ],
  bedroom: [
    'Make the bed',
    'Fold three pieces of clothing',
    'Put away one item that is out of place',
    'Straighten items on the nightstand',
    'Open the curtains or blinds',
    'Fluff the pillows',
    'Make sure the closet is closed',
    'Put a book back on the shelf',
    'Plug in a phone charger',
    'Straighten the shoes by the closet',
    'Empty a small trash can',
    'Set an alarm on a clock',
    'Fold the blanket at the foot of the bed',
    'Tidy the top of the dresser',
    'Turn off a light',
  ],
  outdoor: [
    'Check the mailbox',
    'Pick up 3 pieces of debris from the yard',
    'Check that the porch light works',
    'Straighten a chair or item on the porch',
    'Check if the front door is locked',
    'Water a plant outside',
    'Check that the trash cans are closed',
    'Look for any packages at the door',
    'Check that a nearby car is locked',
    'Coil up a loose hose or cord',
    'Check the mailbox flag',
    'Sweep the front step',
    'Check that the doorbell works',
    'Look up and name a cloud shape or star',
    'Close the gate if there is one',
  ],
  'any-room': [
    'Do 10 jumping jacks',
    'Type "task complete" in your notes app',
    'Hum your favorite song for 10 seconds',
    'Find something red and touch it',
    'Do 5 pushups',
    'Balance on one foot for 10 seconds',
    'Find a clock and check the time',
    'Count the windows in the room you are in',
    'Say the alphabet backwards from Z to A',
    'Find something blue and touch it',
    'Do a silly dance for 5 seconds',
    'Check your phone battery percentage',
    'Find a book and read its first line',
    'Snap your fingers 10 times',
    'Look out a window and name what you see',
  ],
};

export const ROOM_TYPES = Object.keys(raw) as RoomType[];

export const ALL_TASKS: Task[] = ROOM_TYPES.flatMap((room) =>
  raw[room].map((text, i) => ({ id: `${room}-${i}`, room, text }))
);
